// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NodeConnectionView: typeof import('./src/components/node/NodeConnectionView.vue')['default']
    NodeEditor: typeof import('./src/components/node/NodeEditor.vue')['default']
    NodeParameters: typeof import('./src/components/node/parameters/NodeParameters.vue')['default']
    NodeView: typeof import('./src/components/node/NodeView.vue')['default']
    ParamCodeEditor: typeof import('./src/components/node/parameters/ParamCodeEditor.vue')['default']
    SelectBox: typeof import('./src/components/SelectBox.vue')['default']
    ShortcutReceiver: typeof import('./src/components/ShortcutReceiver.vue')['default']
    StoryboardEditor: typeof import('./src/components/StoryboardEditor.vue')['default']
  }
}
